//go:build gonavi_full_drivers || gonavi_firebird_driver

package db

import (
	"context"
	"fmt"
	"os"
	"slices"
	"strings"
	"testing"
	"time"

	"GoNavi-Wails/internal/connection"
)

// TestFirebirdLiveSmoke 连真实 Firebird：GONAVI_FIREBIRD_TEST_TARGETS 是逗号分隔的 host:port=数据库路径，账号来自
// GONAVI_FIREBIRD_TEST_USER / GONAVI_FIREBIRD_TEST_PASSWORD（缺省 SYSDBA / masterkey）。在库里建临时对象，覆盖版本、
// 元数据、建表语句与例程定义、取值、网格提交（含失败回滚）、托管事务与查询取消。
func TestFirebirdLiveSmoke(t *testing.T) {
	raw := strings.TrimSpace(os.Getenv("GONAVI_FIREBIRD_TEST_TARGETS"))
	if raw == "" {
		t.Skip("set GONAVI_FIREBIRD_TEST_TARGETS=host:port=/path/db.fdb[,...] to run live smoke tests")
	}
	for _, target := range strings.Split(raw, ",") {
		addr, database, _ := strings.Cut(strings.TrimSpace(target), "=")
		t.Run(addr, func(t *testing.T) {
			client := connectFirebirdLive(t, addr, database)
			defer client.Close()
			variant, version := client.DriverVariantInfo()
			t.Logf("server version %s, variant %s", version, variant)
			if variant == "" || version == "" {
				t.Fatalf("variant %q version %q", variant, version)
			}
			fb3, fb4 := client.atLeast("3.0"), client.atLeast("4.0")
			for _, statement := range []string{"DROP PACKAGE GN_PKG", "DROP FUNCTION GN_DOUBLE", "DROP TRIGGER GN_ITEMS_BI", "DROP PROCEDURE GN_PRICED",
				"DROP VIEW GN_BIG_ITEMS", "DROP TABLE GN_ITEMS", "DROP TABLE GN_GROUPS", "DROP SEQUENCE GN_SEQ"} {
				_, _ = client.Exec(statement)
			}
			extra := ""
			if fb3 {
				extra += ",\n    flag BOOLEAN DEFAULT TRUE,\n    serial_no INTEGER GENERATED BY DEFAULT AS IDENTITY"
			}
			if fb4 {
				extra += ",\n    stamp_tz TIMESTAMP WITH TIME ZONE,\n    big INT128,\n    df DECFLOAT(34),\n    bin BINARY(4)"
			}
			mustExec(t, client, "CREATE TABLE gn_groups (gid INTEGER NOT NULL PRIMARY KEY, title VARCHAR(40))")
			mustExec(t, client, `CREATE TABLE gn_items (
    id INTEGER NOT NULL,
    gid INTEGER,
    code CHAR(8) DEFAULT 'X' NOT NULL,
    price NUMERIC(12,2) DEFAULT 1.50,
    made DATE,
    clock TIME,
    stamp TIMESTAMP,
    ratio DOUBLE PRECISION,
    note BLOB SUB_TYPE TEXT,
    payload BLOB`+extra+`,
    CONSTRAINT pk_gn_items PRIMARY KEY (id),
    CONSTRAINT uq_gn_items_code UNIQUE (code),
    CONSTRAINT ck_gn_items_price CHECK (price >= 0),
    CONSTRAINT fk_gn_items_group FOREIGN KEY (gid) REFERENCES gn_groups (gid) ON DELETE CASCADE
)`)
			mustExec(t, client, "CREATE DESCENDING INDEX idx_gn_items_made ON gn_items (made, gid)")
			mustExec(t, client, "COMMENT ON TABLE gn_items IS '商品'")
			mustExec(t, client, "COMMENT ON COLUMN gn_items.code IS '编码'")
			mustExec(t, client, "CREATE VIEW gn_big_items AS SELECT id, price FROM gn_items WHERE price > 100")
			mustExec(t, client, "CREATE SEQUENCE gn_seq")
			mustExec(t, client, "CREATE OR ALTER PROCEDURE gn_priced (p_min NUMERIC(12,2)) RETURNS (id INTEGER, price NUMERIC(12,2)) AS BEGIN FOR SELECT id, price FROM gn_items WHERE price >= :p_min INTO :id, :price DO SUSPEND; END")
			mustExec(t, client, "CREATE OR ALTER TRIGGER gn_items_bi FOR gn_items ACTIVE BEFORE INSERT POSITION 0 AS BEGIN IF (NEW.id IS NULL) THEN NEW.id = NEXT VALUE FOR gn_seq; END")
			if fb3 {
				mustExec(t, client, "CREATE OR ALTER FUNCTION gn_double (p INTEGER) RETURNS INTEGER AS BEGIN RETURN p * 2; END")
				mustExec(t, client, "CREATE OR ALTER PACKAGE gn_pkg AS BEGIN FUNCTION twice(p INTEGER) RETURNS INTEGER; END")
				mustExec(t, client, "RECREATE PACKAGE BODY gn_pkg AS BEGIN FUNCTION twice(p INTEGER) RETURNS INTEGER AS BEGIN RETURN p * 2; END END")
			}
			defer func() {
				// 前面的步骤在连接池的多条连接上用过这些对象：DROP 不能因为闲置连接持有对象而失败或卡住。
				statements := []string{"DROP TRIGGER GN_ITEMS_BI", "DROP PROCEDURE GN_PRICED", "DROP VIEW GN_BIG_ITEMS", "DROP TABLE GN_ITEMS", "DROP TABLE GN_GROUPS", "DROP SEQUENCE GN_SEQ"}
				if fb3 {
					statements = append([]string{"DROP PACKAGE GN_PKG", "DROP FUNCTION GN_DOUBLE"}, statements...)
				}
				for _, statement := range statements {
					if _, err := client.Exec(statement); err != nil {
						t.Errorf("cleanup %s: %v", statement, err)
					}
				}
			}()

			databases, _ := client.GetDatabases()
			tables, err := client.GetTables(databases[0])
			if err != nil || !slices.Contains(tables, "GN_ITEMS") || slices.Contains(tables, "GN_BIG_ITEMS") || slices.Contains(tables, "RDB$RELATIONS") {
				t.Fatalf("databases %v tables %v %v", databases, tables, err)
			}
			columns, err := client.GetColumns("", "gn_items")
			if err != nil {
				t.Fatal(err)
			}
			byName := map[string]connection.ColumnDefinition{}
			for _, column := range columns {
				byName[column.Name] = column
				t.Logf("column %s %s key=%s null=%s default=%v extra=%s comment=%q", column.Name, column.Type, column.Key, column.Nullable, firebirdLiveText(column.Default), column.Extra, column.Comment)
			}
			if byName["ID"].Key != "PRI" || byName["CODE"].Key != "UNI" || byName["CODE"].Type != "CHAR(8)" || byName["CODE"].Comment != "编码" ||
				byName["PRICE"].Type != "NUMERIC(12,2)" || firebirdLiveText(byName["PRICE"].Default) != "1.50" || byName["NOTE"].Type != "BLOB SUB_TYPE TEXT" {
				t.Fatalf("column metadata %+v", byName)
			}
			if fb3 && byName["SERIAL_NO"].Extra != "auto_increment" {
				t.Fatalf("identity column %+v", byName["SERIAL_NO"])
			}
			if fb4 && (byName["STAMP_TZ"].Type != "TIMESTAMP WITH TIME ZONE" || byName["BIG"].Type != "INT128" || byName["BIN"].Type != "BINARY(4)") {
				t.Fatalf("4.0 types %+v", byName)
			}
			indexes, err := client.GetIndexes("", "GN_ITEMS")
			if err != nil || len(indexes) < 4 {
				t.Fatalf("indexes %+v %v", indexes, err)
			}
			foreignKeys, err := client.GetForeignKeys("", "GN_ITEMS")
			if err != nil || len(foreignKeys) != 1 || foreignKeys[0].RefTableName != "GN_GROUPS" {
				t.Fatalf("foreign keys %+v %v", foreignKeys, err)
			}
			triggers, err := client.GetTriggers("", "GN_ITEMS")
			if err != nil || len(triggers) != 1 || triggers[0].Timing != "BEFORE" || triggers[0].Event != "INSERT" {
				t.Fatalf("triggers %+v %v", triggers, err)
			}
			definitions := map[string][]string{
				"GN_ITEMS":     {"CREATE TABLE \"GN_ITEMS\"", "CONSTRAINT \"PK_GN_ITEMS\" PRIMARY KEY (\"ID\")", "ON DELETE CASCADE", "CHECK (price >= 0)", "CREATE DESCENDING INDEX \"IDX_GN_ITEMS_MADE\"", "COMMENT ON COLUMN \"GN_ITEMS\".\"CODE\" IS '编码'"},
				"GN_BIG_ITEMS": {"CREATE VIEW \"GN_BIG_ITEMS\" (\"ID\", \"PRICE\") AS"},
				"gn_priced":    {"CREATE OR ALTER PROCEDURE \"GN_PRICED\" (\"P_MIN\" NUMERIC(12,2))", "RETURNS (\"ID\" INTEGER, \"PRICE\" NUMERIC(12,2))", "AS\n"},
				"GN_ITEMS_BI":  {"CREATE OR ALTER TRIGGER \"GN_ITEMS_BI\" FOR \"GN_ITEMS\" ACTIVE BEFORE INSERT POSITION 0", "NEXT VALUE FOR gn_seq"},
				"GN_SEQ":       {"CREATE SEQUENCE \"GN_SEQ\""},
			}
			if fb3 {
				definitions["GN_DOUBLE"] = []string{"CREATE OR ALTER FUNCTION \"GN_DOUBLE\" (\"P\" INTEGER)", "RETURNS INTEGER", "RETURN p * 2"}
				definitions["GN_PKG"] = []string{"CREATE OR ALTER PACKAGE \"GN_PKG\"", "RECREATE PACKAGE BODY \"GN_PKG\""}
			}
			for name, fragments := range definitions {
				definition, err := client.GetCreateStatement("", name)
				if err != nil {
					t.Fatalf("definition of %s: %v", name, err)
				}
				for _, fragment := range fragments {
					if !strings.Contains(definition, fragment) {
						t.Fatalf("definition of %s lacks %q:\n%s", name, fragment, definition)
					}
				}
				if name == "GN_ITEMS" {
					t.Logf("ddl:\n%s", definition)
				}
			}

			mustExec(t, client, "INSERT INTO gn_groups VALUES (1, 'g1')")
			mustExec(t, client, "INSERT INTO gn_items (gid, code, price, made, clock, stamp, ratio, note, payload) VALUES (1, 'A1', 123.45, '2024-02-29', '13:14:15.1234', '2024-02-29 13:14:15.5', 2.5, '备注', x'DEADBEEF')")
			rows, _, err := client.Query("SELECT id, code, price, made, clock, stamp, ratio, note, payload FROM gn_items")
			if err != nil || len(rows) != 1 {
				t.Fatalf("rows %v %v", rows, err)
			}
			row := rows[0]
			t.Logf("row %#v", row)
			if fmt.Sprint(row["ID"]) != "1" || strings.TrimSpace(fmt.Sprint(row["CODE"])) != "A1" || row["PRICE"] != "123.45" || row["MADE"] != "2024-02-29" || row["CLOCK"] != "13:14:15.1234" || row["NOTE"] != "备注" {
				t.Fatalf("values %#v", row)
			}
			if paged, _, err := client.Query("SELECT id FROM gn_items ORDER BY id ROWS 1 TO 1"); err != nil || len(paged) != 1 {
				t.Fatalf("ROWS pagination %v %v", paged, err)
			}

			changes := connection.ChangeSet{
				Inserts: []map[string]any{{"ID": "200", "GID": "1", "CODE": "B2", "MADE": "2024-03-01", "STAMP": "2024-03-01 08:09:10", "NOTE": strings.Repeat("长", 20000)}},
				Updates: []connection.UpdateRow{{Keys: map[string]any{"ID": "1"}, Values: map[string]any{"PRICE": "99.5", "CLOCK": "08:00:00"}}},
			}
			if err := client.ApplyChanges("GN_ITEMS", changes); err != nil {
				t.Fatalf("apply changes: %v", err)
			}
			checked, _, err := client.Query("SELECT id, price, clock, CHAR_LENGTH(note) AS note_len FROM gn_items ORDER BY id")
			if err != nil || len(checked) != 2 || checked[0]["PRICE"] != "99.5" && checked[0]["PRICE"] != "99.50" || fmt.Sprint(checked[1]["NOTE_LEN"]) != "20000" {
				t.Fatalf("after changes %#v %v", checked, err)
			}
			failing := connection.ChangeSet{
				Inserts: []map[string]any{{"ID": "300", "GID": "1", "CODE": "C3"}},
				Updates: []connection.UpdateRow{{Keys: map[string]any{"ID": "999"}, Values: map[string]any{"PRICE": "1"}}},
			}
			if err := client.ApplyChanges("GN_ITEMS", failing); err == nil {
				t.Fatal("expected failure for missing row")
			}
			if rows, _, _ := client.Query("SELECT id FROM gn_items WHERE id = 300"); len(rows) != 0 {
				t.Fatalf("failed change set was not rolled back: %v", rows)
			}

			execer, err := client.OpenTransactionExecer(context.Background())
			if err != nil {
				t.Fatal(err)
			}
			if _, err := execer.ExecContext(context.Background(), "INSERT INTO gn_groups VALUES (2, 'g2')"); err != nil {
				t.Fatal(err)
			}
			if err := execer.Rollback(); err != nil {
				t.Fatal(err)
			}
			if err := execer.Close(); err != nil {
				t.Fatal(err)
			}
			if rows, _, _ := client.Query("SELECT gid FROM gn_groups WHERE gid = 2"); len(rows) != 0 {
				t.Fatalf("rolled back transaction is visible: %v", rows)
			}

			if os.Getenv("GONAVI_FIREBIRD_SKIP_CANCEL") != "" {
				return
			}
			ctx, cancel := context.WithTimeout(context.Background(), 2*time.Second)
			defer cancel()
			started := time.Now()
			_, _, err = client.QueryContext(ctx, "SELECT COUNT(*) FROM rdb$fields a, rdb$fields b, rdb$fields c WHERE a.rdb$field_name || b.rdb$field_name || c.rdb$field_name LIKE '%zz%q%'")
			if err == nil || time.Since(started) > 20*time.Second {
				t.Fatalf("cancel: err=%v after %s", err, time.Since(started))
			}
			t.Logf("cancelled after %s: %v", time.Since(started), err)
			if _, _, err := client.Query("SELECT 1 AS one FROM rdb$database"); err != nil {
				t.Fatalf("connection unusable after cancel: %v", err)
			}
		})
	}
}

func connectFirebirdLive(t *testing.T, addr, database string) *FirebirdDB {
	t.Helper()
	user := os.Getenv("GONAVI_FIREBIRD_TEST_USER")
	if user == "" {
		user = "SYSDBA"
	}
	config := liveConfig(t, "firebird", addr, user, "")
	config.Password = os.Getenv("GONAVI_FIREBIRD_TEST_PASSWORD")
	if config.Password == "" {
		config.Password = "masterkey"
	}
	config.ConnectionParams = "databasePath=" + database
	client := &FirebirdDB{}
	if err := client.Connect(config); err != nil {
		t.Fatalf("connect %s: %v", addr, err)
	}
	return client
}

func firebirdLiveText(value *string) string {
	if value == nil {
		return "<nil>"
	}
	return *value
}
