//go:build gonavi_full_drivers || gonavi_firebird_driver

package db

import (
	"fmt"
	"strings"
)

// Firebird 没有 SHOW CREATE：表的建表语句按 RDB$ 系统表拼出来（列、约束、索引、注释），视图、存储过程、函数、触发器、
// 包用系统表里保存的源码补上头部，生成器给出 CREATE SEQUENCE 与当前值。

// firebirdObjectKinds 是按名字查找对象时依次检查的系统表（3.0 起才有 PSQL 函数与包）。
var firebirdObjectKinds = []struct {
	kind, query string
	minVersion  string
}{
	{"RELATION", "SELECT CASE WHEN RDB$VIEW_BLR IS NULL THEN 'TABLE' ELSE 'VIEW' END AS kind FROM RDB$RELATIONS WHERE RDB$RELATION_NAME = ?", ""},
	{"PROCEDURE", "SELECT 'PROCEDURE' AS kind FROM RDB$PROCEDURES WHERE RDB$PROCEDURE_NAME = ?", ""},
	{"FUNCTION", "SELECT 'FUNCTION' AS kind FROM RDB$FUNCTIONS WHERE RDB$FUNCTION_NAME = ? AND RDB$PACKAGE_NAME IS NULL AND RDB$FUNCTION_SOURCE IS NOT NULL", "3.0"},
	{"TRIGGER", "SELECT 'TRIGGER' AS kind FROM RDB$TRIGGERS WHERE RDB$TRIGGER_NAME = ?", ""},
	{"SEQUENCE", "SELECT 'SEQUENCE' AS kind FROM RDB$GENERATORS WHERE RDB$GENERATOR_NAME = ?", ""},
	{"PACKAGE", "SELECT 'PACKAGE' AS kind FROM RDB$PACKAGES WHERE RDB$PACKAGE_NAME = ?", "3.0"},
}

// objectKind 返回对象类型（TABLE、VIEW、PROCEDURE、FUNCTION、TRIGGER、SEQUENCE、PACKAGE）与库里的精确名字。
func (f *FirebirdDB) objectKind(name string) (string, string) {
	name = strings.Trim(strings.TrimSpace(name), `"`)
	if _, object, ok := strings.Cut(name, "."); ok && !strings.Contains(object, ".") {
		name = object
	}
	candidates := []string{name}
	if upper := strings.ToUpper(name); upper != name {
		candidates = append(candidates, upper)
	}
	for _, candidate := range candidates {
		for _, kind := range firebirdObjectKinds {
			if kind.minVersion != "" && !f.atLeast(kind.minVersion) {
				continue
			}
			rows, err := f.queryArgs(kind.query, candidate)
			if err == nil && len(rows) > 0 {
				return firebirdText(rows[0]["KIND"]), candidate
			}
		}
	}
	return "", name
}

func (f *FirebirdDB) GetCreateStatement(_ string, objectName string) (string, error) {
	kind, name := f.objectKind(objectName)
	switch kind {
	case "TABLE":
		return f.tableDefinition(name)
	case "VIEW":
		return f.viewDefinition(name)
	case "PROCEDURE":
		return f.procedureDefinition(name)
	case "FUNCTION":
		return f.functionDefinition(name)
	case "TRIGGER":
		return f.triggerDefinition(name)
	case "SEQUENCE":
		return f.sequenceDefinition(name)
	case "PACKAGE":
		return f.packageDefinition(name)
	}
	return "", localizedDatabaseRuntimeError("db.backend.error.firebird_object_not_found", map[string]any{"name": objectName})
}

// databaseCharset 是库的默认字符集（与它相同的列不重复写 CHARACTER SET）。
func (f *FirebirdDB) databaseCharset() string {
	rows, err := f.queryArgs("SELECT TRIM(RDB$CHARACTER_SET_NAME) AS cs FROM RDB$DATABASE")
	if err != nil || len(rows) == 0 {
		return ""
	}
	return firebirdText(rows[0]["CS"])
}

// columnDefinition 生成一列的定义：计算列写 COMPUTED BY，标识列写 GENERATED ... AS IDENTITY。
func firebirdColumnDefinition(column firebirdColumn, binaryTypes bool, databaseCharset string) string {
	var builder strings.Builder
	builder.WriteString(firebirdQuoteIdent(column.name))
	builder.WriteByte(' ')
	if column.computed != "" {
		builder.WriteString("COMPUTED BY " + column.computed)
		return builder.String()
	}
	builder.WriteString(column.field.typeName(binaryTypes))
	charset := column.field.charset
	if isFirebirdCharacterType(column.field.fieldType) && charset != "" && !strings.EqualFold(charset, "OCTETS") &&
		!strings.EqualFold(charset, databaseCharset) {
		builder.WriteString(" CHARACTER SET " + charset)
	}
	switch column.identity {
	case 0:
		builder.WriteString(" GENERATED ALWAYS AS IDENTITY")
	case 1:
		builder.WriteString(" GENERATED BY DEFAULT AS IDENTITY")
	}
	if value, ok := firebirdDefaultValue(column.defaultSrc); ok {
		builder.WriteString(" DEFAULT " + value)
	}
	if column.notNull {
		builder.WriteString(" NOT NULL")
	}
	return builder.String()
}

func isFirebirdCharacterType(fieldType int) bool {
	return fieldType == firebirdTypeChar || fieldType == firebirdTypeVarchar || fieldType == firebirdTypeCString
}

func firebirdQuotedList(names []string) string {
	quoted := make([]string, len(names))
	for i, name := range names {
		quoted[i] = firebirdQuoteIdent(name)
	}
	return strings.Join(quoted, ", ")
}

// firebirdConstraintPrefix 生成 CONSTRAINT 名前缀（系统生成的名字省略，由服务端重新生成）。
func firebirdConstraintPrefix(name string) string {
	if firebirdGeneratedConstraintName(name) {
		return ""
	}
	return "CONSTRAINT " + firebirdQuoteIdent(name) + " "
}

func (f *FirebirdDB) tableDefinition(table string) (string, error) {
	columns, err := f.loadColumns(table)
	if err != nil {
		return "", err
	}
	constraints, err := f.constraints(table)
	if err != nil {
		return "", err
	}
	foreignKeys, err := f.loadForeignKeys(table)
	if err != nil {
		return "", err
	}
	binaryTypes := f.atLeast("4.0")
	charset := f.databaseCharset()
	lines := make([]string, 0, len(columns)+len(constraints))
	for _, column := range columns {
		lines = append(lines, "    "+firebirdColumnDefinition(column, binaryTypes, charset))
	}
	for _, constraint := range constraints {
		if constraint.kind == "FOREIGN KEY" {
			continue
		}
		lines = append(lines, fmt.Sprintf("    %s%s (%s)", firebirdConstraintPrefix(constraint.name), constraint.kind, firebirdQuotedList(constraint.columns)))
	}
	for _, key := range foreignKeys {
		line := fmt.Sprintf("    %sFOREIGN KEY (%s) REFERENCES %s (%s)", firebirdConstraintPrefix(key.name), firebirdQuotedList(key.columns),
			firebirdQuoteIdent(key.refTable), firebirdQuotedList(key.refColumns))
		if key.updateRule != "" && !strings.EqualFold(key.updateRule, "RESTRICT") {
			line += " ON UPDATE " + key.updateRule
		}
		if key.deleteRule != "" && !strings.EqualFold(key.deleteRule, "RESTRICT") {
			line += " ON DELETE " + key.deleteRule
		}
		lines = append(lines, line)
	}
	checks, err := f.queryArgs(`SELECT DISTINCT TRIM(rc.RDB$CONSTRAINT_NAME) AS cname, t.RDB$TRIGGER_SOURCE AS src
FROM RDB$RELATION_CONSTRAINTS rc
JOIN RDB$CHECK_CONSTRAINTS cc ON cc.RDB$CONSTRAINT_NAME = rc.RDB$CONSTRAINT_NAME
JOIN RDB$TRIGGERS t ON t.RDB$TRIGGER_NAME = cc.RDB$TRIGGER_NAME
WHERE rc.RDB$RELATION_NAME = ? AND rc.RDB$CONSTRAINT_TYPE = 'CHECK' AND t.RDB$TRIGGER_TYPE = 1`, table)
	if err != nil {
		return "", err
	}
	for _, check := range checks {
		lines = append(lines, "    "+firebirdConstraintPrefix(firebirdText(check["CNAME"]))+firebirdText(check["SRC"]))
	}
	statements := []string{fmt.Sprintf("CREATE TABLE %s (\n%s\n);", firebirdQuoteIdent(table), strings.Join(lines, ",\n"))}

	indexes, err := f.loadIndexes(table)
	if err != nil {
		return "", err
	}
	for _, index := range indexes {
		if index.constraintKind != "" {
			continue
		}
		var modifiers string
		if index.unique {
			modifiers += "UNIQUE "
		}
		if index.descending {
			modifiers += "DESCENDING "
		}
		target := "(" + firebirdQuotedList(index.columns) + ")"
		if len(index.columns) == 0 && index.expression != "" {
			target = "COMPUTED BY " + index.expression
		}
		statements = append(statements, fmt.Sprintf("CREATE %sINDEX %s ON %s %s;", modifiers, firebirdQuoteIdent(index.name), firebirdQuoteIdent(table), target))
	}
	rows, err := f.queryArgs("SELECT RDB$DESCRIPTION AS descr FROM RDB$RELATIONS WHERE RDB$RELATION_NAME = ?", table)
	if err == nil && len(rows) > 0 {
		if comment := firebirdText(rows[0]["DESCR"]); comment != "" {
			statements = append(statements, fmt.Sprintf("COMMENT ON TABLE %s IS %s;", firebirdQuoteIdent(table), firebirdLiteral(comment)))
		}
	}
	for _, column := range columns {
		if column.comment != "" {
			statements = append(statements, fmt.Sprintf("COMMENT ON COLUMN %s.%s IS %s;", firebirdQuoteIdent(table), firebirdQuoteIdent(column.name), firebirdLiteral(column.comment)))
		}
	}
	return strings.Join(statements, "\n"), nil
}

func (f *FirebirdDB) viewDefinition(view string) (string, error) {
	rows, err := f.queryArgs("SELECT RDB$VIEW_SOURCE AS src FROM RDB$RELATIONS WHERE RDB$RELATION_NAME = ?", view)
	if err != nil {
		return "", err
	}
	if len(rows) == 0 {
		return "", localizedDatabaseRuntimeError("db.backend.error.firebird_object_not_found", map[string]any{"name": view})
	}
	columns, err := f.loadColumns(view)
	if err != nil {
		return "", err
	}
	names := make([]string, len(columns))
	for i, column := range columns {
		names[i] = column.name
	}
	return fmt.Sprintf("CREATE VIEW %s (%s) AS\n%s;", firebirdQuoteIdent(view), firebirdQuotedList(names),
		strings.TrimSpace(firebirdRawText(rows[0]["SRC"]))), nil
}

// firebirdParameter 是存储过程 / 函数的一个参数。
type firebirdParameter struct {
	name       string
	field      firebirdField
	output     bool
	defaultSrc string
}

func (p firebirdParameter) definition(binaryTypes bool) string {
	text := firebirdQuoteIdent(p.name) + " " + p.field.typeName(binaryTypes)
	if value, ok := firebirdDefaultValue(p.defaultSrc); ok {
		text += " DEFAULT " + value
	}
	return text
}

const firebirdParameterFieldColumns = `fd.RDB$FIELD_TYPE AS ftype, fd.RDB$FIELD_SUB_TYPE AS subtype, fd.RDB$FIELD_LENGTH AS flen,
	fd.RDB$FIELD_PRECISION AS fprec, fd.RDB$FIELD_SCALE AS fscale, fd.RDB$CHARACTER_LENGTH AS clen, TRIM(cs.RDB$CHARACTER_SET_NAME) AS charset`

func firebirdParameterField(row map[string]interface{}) firebirdField {
	return firebirdField{
		fieldType: firebirdInt(row["FTYPE"]), subType: firebirdInt(row["SUBTYPE"]), length: firebirdInt(row["FLEN"]),
		precision: firebirdInt(row["FPREC"]), scale: firebirdInt(row["FSCALE"]), charLength: firebirdInt(row["CLEN"]),
		charset: firebirdText(row["CHARSET"]),
	}
}

// firebirdBody 返回 "AS" 开头的过程体：存储过程的源码不含 AS，触发器的源码自带。
func firebirdBody(source string) string {
	text := strings.TrimSpace(source)
	if len(text) >= 3 && strings.EqualFold(text[:2], "AS") && (text[2] == ' ' || text[2] == '\n' || text[2] == '\r' || text[2] == '\t') {
		return text
	}
	return "AS\n" + text
}

func (f *FirebirdDB) procedureDefinition(procedure string) (string, error) {
	packageFilter := ""
	if f.atLeast("3.0") {
		packageFilter = " AND pp.RDB$PACKAGE_NAME IS NULL"
	}
	params, err := f.queryArgs(`SELECT TRIM(pp.RDB$PARAMETER_NAME) AS pname, pp.RDB$PARAMETER_TYPE AS ptype, pp.RDB$DEFAULT_SOURCE AS defsrc, `+
		firebirdParameterFieldColumns+`
FROM RDB$PROCEDURE_PARAMETERS pp
JOIN RDB$FIELDS fd ON fd.RDB$FIELD_NAME = pp.RDB$FIELD_SOURCE
LEFT JOIN RDB$CHARACTER_SETS cs ON cs.RDB$CHARACTER_SET_ID = fd.RDB$CHARACTER_SET_ID
WHERE pp.RDB$PROCEDURE_NAME = ?`+packageFilter+`
ORDER BY pp.RDB$PARAMETER_TYPE, pp.RDB$PARAMETER_NUMBER`, procedure)
	if err != nil {
		return "", err
	}
	binaryTypes := f.atLeast("4.0")
	var inputs, outputs []string
	for _, row := range params {
		parameter := firebirdParameter{name: firebirdText(row["PNAME"]), field: firebirdParameterField(row), defaultSrc: firebirdRawText(row["DEFSRC"])}
		if firebirdInt(row["PTYPE"]) == 1 {
			outputs = append(outputs, parameter.definition(binaryTypes))
		} else {
			inputs = append(inputs, parameter.definition(binaryTypes))
		}
	}
	rows, err := f.queryArgs("SELECT RDB$PROCEDURE_SOURCE AS src FROM RDB$PROCEDURES WHERE RDB$PROCEDURE_NAME = ?", procedure)
	if err != nil || len(rows) == 0 {
		return "", err
	}
	header := "CREATE OR ALTER PROCEDURE " + firebirdQuoteIdent(procedure)
	if len(inputs) > 0 {
		header += " (" + strings.Join(inputs, ", ") + ")"
	}
	if len(outputs) > 0 {
		header += "\nRETURNS (" + strings.Join(outputs, ", ") + ")"
	}
	return header + "\n" + firebirdBody(firebirdRawText(rows[0]["SRC"])), nil
}

func (f *FirebirdDB) functionDefinition(function string) (string, error) {
	rows, err := f.queryArgs(`SELECT RDB$FUNCTION_SOURCE AS src, RDB$RETURN_ARGUMENT AS ret, RDB$DETERMINISTIC_FLAG AS det
FROM RDB$FUNCTIONS WHERE RDB$FUNCTION_NAME = ? AND RDB$PACKAGE_NAME IS NULL`, function)
	if err != nil || len(rows) == 0 {
		return "", err
	}
	returnPosition := firebirdInt(rows[0]["RET"])
	args, err := f.queryArgs(`SELECT a.RDB$ARGUMENT_POSITION AS pos, TRIM(a.RDB$ARGUMENT_NAME) AS pname, a.RDB$DEFAULT_SOURCE AS defsrc, `+
		firebirdParameterFieldColumns+`
FROM RDB$FUNCTION_ARGUMENTS a
JOIN RDB$FIELDS fd ON fd.RDB$FIELD_NAME = a.RDB$FIELD_SOURCE
LEFT JOIN RDB$CHARACTER_SETS cs ON cs.RDB$CHARACTER_SET_ID = fd.RDB$CHARACTER_SET_ID
WHERE a.RDB$FUNCTION_NAME = ? AND a.RDB$PACKAGE_NAME IS NULL
ORDER BY a.RDB$ARGUMENT_POSITION`, function)
	if err != nil {
		return "", err
	}
	binaryTypes := f.atLeast("4.0")
	var inputs []string
	returns := ""
	for _, row := range args {
		field := firebirdParameterField(row)
		if firebirdInt(row["POS"]) == returnPosition && firebirdText(row["PNAME"]) == "" {
			returns = field.typeName(binaryTypes)
			continue
		}
		inputs = append(inputs, firebirdParameter{name: firebirdText(row["PNAME"]), field: field, defaultSrc: firebirdRawText(row["DEFSRC"])}.definition(binaryTypes))
	}
	header := fmt.Sprintf("CREATE OR ALTER FUNCTION %s (%s)\nRETURNS %s", firebirdQuoteIdent(function), strings.Join(inputs, ", "), returns)
	if firebirdInt(rows[0]["DET"]) == 1 {
		header += " DETERMINISTIC"
	}
	return header + "\n" + firebirdBody(firebirdRawText(rows[0]["SRC"])), nil
}

func (f *FirebirdDB) triggerDefinition(trigger string) (string, error) {
	triggers, err := f.loadTriggers("", trigger)
	if err != nil || len(triggers) == 0 {
		return "", err
	}
	current := triggers[0]
	state := "ACTIVE"
	if current.inactive {
		state = "INACTIVE"
	}
	header := "CREATE OR ALTER TRIGGER " + firebirdQuoteIdent(current.name)
	if timing, events := firebirdTriggerTiming(current.triggerType); timing != "" && current.table != "" {
		header += fmt.Sprintf(" FOR %s %s %s %s POSITION %d", firebirdQuoteIdent(current.table), state, timing, strings.Join(events, " OR "), current.position)
	} else {
		header += fmt.Sprintf(" %s %s POSITION %d", state, firebirdDatabaseTriggerEvent(current.triggerType), current.position)
	}
	return header + "\n" + firebirdBody(current.source), nil
}

// firebirdDatabaseTriggerEvent 解码数据库级触发器的事件（8192 起依次为连接、断开、事务开始、提交、回滚）。
func firebirdDatabaseTriggerEvent(triggerType int) string {
	events := map[int]string{8192: "ON CONNECT", 8193: "ON DISCONNECT", 8194: "ON TRANSACTION START", 8195: "ON TRANSACTION COMMIT", 8196: "ON TRANSACTION ROLLBACK"}
	if event, ok := events[triggerType]; ok {
		return event
	}
	return fmt.Sprintf("/* trigger type %d */", triggerType)
}

// sequenceDefinition 生成 CREATE SEQUENCE，并在生成器用过时补一条 RESTART 还原当前值：4.0 起 RESTART WITH n 的下一个值
// 就是 n，之前的版本是 n + 步长；3.0 起能从初始值判断是否用过，2.5 总是补上。
func (f *FirebirdDB) sequenceDefinition(sequence string) (string, error) {
	statement := "CREATE SEQUENCE " + firebirdQuoteIdent(sequence)
	initial, increment, known := 0, 1, false
	if f.atLeast("3.0") {
		rows, err := f.queryArgs("SELECT RDB$INITIAL_VALUE AS initval, RDB$GENERATOR_INCREMENT AS incr FROM RDB$GENERATORS WHERE RDB$GENERATOR_NAME = ?", sequence)
		if err == nil && len(rows) > 0 {
			initial, increment, known = firebirdInt(rows[0]["INITVAL"]), max(firebirdInt(rows[0]["INCR"]), 1), true
			statement += fmt.Sprintf(" START WITH %d INCREMENT BY %d", initial, increment)
		}
	}
	statements := []string{statement + ";"}
	rows, err := f.queryArgs(fmt.Sprintf("SELECT GEN_ID(%s, 0) AS currval FROM RDB$DATABASE", firebirdQuoteIdent(sequence)))
	if err == nil && len(rows) > 0 {
		current := firebirdInt(rows[0]["CURRVAL"])
		if !known || current != initial-increment {
			restart := current
			if f.atLeast("4.0") {
				restart = current + increment
			}
			statements = append(statements, fmt.Sprintf("ALTER SEQUENCE %s RESTART WITH %d;", firebirdQuoteIdent(sequence), restart))
		}
	}
	return strings.Join(statements, "\n"), nil
}

func (f *FirebirdDB) packageDefinition(pkg string) (string, error) {
	rows, err := f.queryArgs("SELECT RDB$PACKAGE_HEADER_SOURCE AS header, RDB$PACKAGE_BODY_SOURCE AS body FROM RDB$PACKAGES WHERE RDB$PACKAGE_NAME = ?", pkg)
	if err != nil || len(rows) == 0 {
		return "", err
	}
	statements := []string{fmt.Sprintf("CREATE OR ALTER PACKAGE %s\n%s;", firebirdQuoteIdent(pkg), firebirdBody(firebirdRawText(rows[0]["HEADER"])))}
	if body := firebirdRawText(rows[0]["BODY"]); body != "" {
		statements = append(statements, fmt.Sprintf("RECREATE PACKAGE BODY %s\n%s;", firebirdQuoteIdent(pkg), firebirdBody(body)))
	}
	return strings.Join(statements, "\n"), nil
}
